name: Sync from Upstream Template

on:
  schedule:
    - cron: '0 */6 * * *' # каждые 6 часов
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream repo
        run: |
          git remote add upstream https://github.com/DefenderOfBasic/obsidian-quartz-template.git
          git fetch upstream

      - name: Merge upstream/main into main with exclusions
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories --no-edit || true

          # Отменяем нежелательные изменения
          git restore --source=HEAD --staged --worktree index.md quartz.config.ts
          git restore --source=HEAD --staged --worktree .github/workflows/ci.yaml

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if git diff --quiet && git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -am "Sync from upstream (auto-excluding index.md, config, ci.yaml)"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
          fi
