name: Sync Selected Quartz Files

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Clone upstream template
        run: |
          git clone --depth=1 https://github.com/DefenderOfBasic/obsidian-quartz-template.git upstream-template

      - name: Copy only selected safe files
        run: |
          mkdir -p source/quartz
          mkdir -p source/styles

          # Сохраняем твой ci.yaml
          cp -v .github/workflows/ci.yaml ci.yaml.bak || true

          # Копируем только нужные каталоги
          rsync -av upstream-template/source/quartz/ source/quartz/ \
            --exclude 'config.ts' \
            --exclude 'layout.ts'

          rsync -av upstream-template/source/styles/ source/styles/ || true

          # Можно добавить ещё конкретные копируемые пути
          # rsync -av upstream-template/package.json ./ || true

          # Возвращаем сохранённый файл
          mv -v ci.yaml.bak .github/workflows/ci.yaml || true

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Safely sync selected Quartz files from upstream"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
          fi
